/*
 * This Java source file was auto generated by running 'gradle buildInit --type java-library'
 * by 'johan' at '12/9/16 11:59 AM' with Gradle 3.1
 *
 * @author johan, @date 12/9/16 11:59 AM
 */
public class Library {
    public boolean someLibraryMethod() {
        return true;
    }
}
